### ISSUE TITLE
Why none of the themes works for me?

### ISSUE THREAD

**Issue by ZzAntares** [jmblog/color-themes-for-google-code-prettify#12]
Hello, I'm just trying to use any of the themes provided by you but, when I put the stylesheet it looks like this (any theme wraps lines):

`tomorrow.css`
![screen shot 2015-11-29 at 23 33 34](https://cloud.githubusercontent.com/assets/3653680/11464235/2555a5e2-96f2-11e5-9229-fea5a3a9322a.png)

`tomorrow-night.css`
![screen shot 2015-11-29 at 23 41 41](https://cloud.githubusercontent.com/assets/3653680/11464291/c9ed9e2a-96f2-11e5-8e59-4435f9d0a92d.png)

When using the default `prettify.css` code looks good:

![screen shot 2015-11-29 at 23 39 58](https://cloud.githubusercontent.com/assets/3653680/11464273/932a0644-96f2-11e5-81fc-352e52896084.png)

What could be the issue?

Thanks!

**Comment by jmblog** [comment]
@ZzAntares which HTML tag do you use for representing the code section? I guess it would be good if you use `<pre>` or an element with `display: block`.

**Comment by ZzAntares** [comment]
Sorry I've omitted such an important clue, this is the way code is wrapped:

```
<pre><code class="prettyprint lang-php">&lt;?php

use Vendor\Package\SomeClass;

class SampleClass extends SomeClass
{
    public function sayHello()
    {
        echo &quot;Hello world!&quot;;
    }
}
</code></pre>
```

I'm using it in a rails app, my content is parsed from markdown with [redcarpet](https://github.com/vmg/redcarpet) gem.

You think could be because of the nested `<code>` inside `<pre>`?

Also I don't know if it affects in some way but I'm using [twitter bootstrap](https://github.com/twbs/bootstrap-sass).

Thanks for the help!

**Comment by jmblog** [comment]
@ZzAntares There are two ways to solve this issue.

1) Add `prettyprint ` (and `lang-php`) class to `<pre>`, not `<code>`.
2) Add `pre > code.prettyprint { display: block; }` in your stylesheet.

Try either please.

**Comment by ZzAntares** [comment]
@jmblog thanks a lot! I't worked like a charm, for the record I used option 2 because redcarpet seems to not support adding `prettyprint` in `<pre>`.

Thanks again!

**Comment by jmblog** [comment]
:smile:
