### ISSUE TITLE
Tomorrow Night theme broken in Firefox, Safari

### ISSUE THREAD

**Issue by hanxue** [jmblog/color-themes-for-google-code-prettify#16]
Browsers tested:
Chrome 63.0.3234.0
Firefox 56.0
Safari 10.1.2

Chrome: 

![image](https://user-images.githubusercontent.com/760008/31316003-a0e0f56a-ac56-11e7-8b64-9047a9f78e8c.png)

Firefox: 

![image](https://user-images.githubusercontent.com/760008/31316006-acf8152c-ac56-11e7-9a2a-c5021db8f57e.png)

Safari: 

![image](https://user-images.githubusercontent.com/760008/31316013-de663850-ac56-11e7-89bd-1f93b6c32375.png)

Highlighted code:

```html
<pre class="prettyprint lang-sh"><code>
$ git stash apply
On branch features-from-fbone
Your branch is up-to-date with 'origin/features-from-fbone'.

Changes not staged for commit:
&nbsp; (use "git add &lt;file&gt;..." to update what will be committed)
&nbsp; (use "git checkout -- &lt;file&gt;..." to discard changes in working directory)

<span style="white-space: pre;"> </span>modified:&nbsp; &nbsp;model.py
<span style="white-space: pre;"> </span>modified:&nbsp; &nbsp;requirements.txt

</code></pre>
```

**Comment by jmblog** [comment]
@hanxue I tested with Safari 11.0 and Firefox 56.0 and it seems work well. 🤔

https://codepen.io/jmblog/pen/KXoVZz

Do you load the [`run_prettify.js`](https://github.com/google/code-prettify/blob/master/docs/getting_started.md#auto-loader)? The `run_prettify.js` loads not only the JavaScript but also the default theme css, and the Tomorrow Night theme css would not applied expectedly.

Please try loading the `prettify.js` (not `run_prettify.js`) and the theme css [individually.](https://github.com/google/code-prettify/blob/master/docs/getting_started.md#serving-your-own-js--css)

**Comment by hanxue** [comment]
Yep, I did run `run_prettify.js`. I used the theme `atelier-dune-light` previously and it was working. When I switch to `tomorrow-night`, it does not work on Firefox and Safari. 

Switching back to `atelier-dune-light` makes it work on all 3 browsers. 

What is really weird is that Tomorrow Night works only for Chrome. 

The actual URL is [http://hanxue-it.blogspot.com/2017/09/git-stashing-staged-added-changes.html ](http://hanxue-it.blogspot.com/2017/09/git-stashing-staged-added-changes.html ). I have now switch the theme back to Tomorrow Night for troubleshooting purposes. 

These lines are added in the `<head>` section

```html
    <link href='//unpkg.com/code-prettify@latest/loader/prettify.css' rel='stylesheet' type='text/css'/>
    <link href='//unpkg.com/color-themes-for-google-code-prettify@latest/dist/themes/tomorrow-night.min.css' rel='stylesheet' type='text/css'/>
    <script src='//unpkg.com/code-prettify@latest/loader/run_prettify.js'/>
```

**Comment by jmblog** [comment]
@hanxue I've checked your page and it doesn't work on Chrome (v61).

![image](https://user-images.githubusercontent.com/86085/31364149-dda7dea8-ad9d-11e7-9c02-c597e5601ea7.png)

The `prettify.css` is loaded twice. The second one is loaded by `run_prettify.js` and it overwrites the styles of Tomorrow Night.

![image](https://user-images.githubusercontent.com/86085/31364118-adb88184-ad9d-11e7-8830-fe971d17ca09.png)

I don't know why the `atelier-dune-light` worked fine, but It might work well if the theme css file is loaded after the `prettify.css`.

Anyway, the themes stylesheets are not assumed to be used with the `prettify.css`.

Can you change the `<head>` section and the `<body>` like this?

```html
<head>
  <link href='//unpkg.com/color-themes-for-google-code-prettify@latest/dist/themes/tomorrow-night.min.css' rel='stylesheet' type='text/css'/>
  <script src='//unpkg.com/code-prettify@latest/src/prettify.js' />
</head>
<body onload="PR.prettyPrint()">
...
```

**Comment by hanxue** [comment]
@jmblog Thank you. You are right, `run_prettify.js` loads prettify.js and the CSS file twice. When I remove it, the website uses the correct theme now. 

I have a few further questions, 

1. What is the difference between `src/prettify.js` and `loader/prettify.js`, and which one should I link from HTML?
2. If I use `loader/prettify.js` then I do not need to manually link to `loader/prettify.css` ?

I have updated to

```html
    <link href='//unpkg.com/color-themes-for-google-code-prettify@latest/dist/themes/tomorrow-night.min.css' rel='stylesheet' type='text/css'/>
    <script src='//unpkg.com/code-prettify@latest/src/prettify.js' type='text/javascript'/>
```

**Comment by jmblog** [comment]
@hanxue 👍 

1. I guess the `loader/prettify.js` is a minified version of `src/prettify.js`. I recommend to use `loader/prettify.js` to save your loading time.
2. Yes. Please link the theme css file **instead of** `loader/prettify.css`.

**Comment by hanxue** [comment]
Thank you very much for time and effort to help me solve the problem!
