### ISSUE TITLE
Bower support?

### ISSUE THREAD

**Issue by maxmert** [jmblog/color-themes-for-google-code-prettify#5]
Hello! Thank you for this beauty. Are you planning to add a bower support. It will be easier to install it.

**Comment by jmblog** [comment]
Fix with https://github.com/jmblog/color-themes-for-google-code-prettify/pull/13

**Comment by jmblog** [comment]
Hmm, https://github.com/dpgowan/color-themes-for-google-code-prettify is already registered.

**Comment by jchamberlain** [comment]
Our app was using @dpgowan's repo, but it's no longer available. I've opened an issue on the Bower registry: bower/registry#238.

**Comment by jmblog** [comment]
Re-registered to this repo!
