### ISSUE TITLE
Desert theme

### ISSUE THREAD

**Issue by techtonik** [jmblog/color-themes-for-google-code-prettify#7]
I ported Vim desert theme by @fugalh to google-prettify, but couldn't figure out where to paste it for pull request. Here is the snippet that I use.

```
.prettyprint {
  background-color: #333; color: #ddd;
  border: 1px solid #888;
  font-size: 90%;
  padding: 5px; 
}
.str { color: #ffa0a0; } /* string  - pink */
.kwd { color: #f0e68c; font-weight: bold; }
.com { color: #87ceeb; } /* comment - skyblue */
.typ { color: #98fb98; } /* type    - lightgreen */
.lit { color: #cd5c5c; } /* literal - darkred */
.pun { color: #fff; }    /* punctuation */
.pln { color: #fff; }    /* plaintext */
.tag { color: #f0e68c; font-weight: bold; } /* html/xml tag    - lightyellow*/
.atn { color: #bdb76b; font-weight: bold; } /* attribute name  - khaki*/
.atv { color: #ffa0a0; } /* attribute value - pink */
.dec { color: #98fb98; } /* decimal         - lightgreen */
```

**Comment by techtonik** [comment]
![desert](https://cloud.githubusercontent.com/assets/515889/5651481/d9c7be2e-96b8-11e4-9684-992227994be1.png)

**Comment by jmblog** [comment]
@techtonik Thank you for the theme. I'll add it asap.

**Comment by jmblog** [comment]
Hi @techtonik,

I found the same theme in the official project page.
https://code.google.com/p/google-code-prettify/source/browse/trunk/styles/desert.css

Have you already try it?

**Comment by techtonik** [comment]
I already forgot that I've added it there https://code.google.com/p/google-code-prettify/issues/detail?id=80 =)

I guess it worth to add a link to https://google-code-prettify.googlecode.com/svn/trunk/styles/index.html so that people could find and evaluate standard themes easier.

**Comment by jmblog** [comment]
@techtonik Thank you for your suggestion. :smile: 
Now I'm starting to rebuild the project page. I'll add the link.

**Comment by jmblog** [comment]
Fix with https://github.com/jmblog/color-themes-for-google-code-prettify/pull/13
